### PR TITLE
Responsive Design for ContributorCard Component using styled-components

### PR DESCRIPTION
**Pull request by 3ein39**
This pull request introduces changes to the `ContributorCard` component to make it responsive using the styled-components library.

Changes include:
- Removal of `display: flex;` on small screens to stack the image and text vertically.
- Addition of `display: flex;` on larger screens to align the image and text horizontally.
- Adjustment of the `ImageContainer` div and the image within it to take up 100% of the width of their parent element on small screens, and have a fixed size of 150px on larger screens.
- Use of styled-components to create `Card` and `ImageContainer` components with media queries for responsive design.

These changes ensure that the `ContributorCard` component adapts to different screen sizes, improving the overall user experience on both small and large screens. The use of styled-components allows for more modular and reusable CSS in JS.

### CODE REVIEW

**Review by alikehel — CHANGES_REQUESTED** [review]
Great work Hussein!

I found some issues.

Screenshot 2023-12-08 105022

Here are my suggestions:

- Make the card take the full width of the page in smaller screens

- Make the card take half width in wider screens so that two cards can be in the same row instead of one like the image below:

Screenshot 2023-12-08 105606

**Comment by 3ein39** [comment]
Hello Aly,
Feel free to take a look and let me know if everything aligns with the expected changes. Thanks again for your collaboration!

**Review by alikehel — CHANGES_REQUESTED** [review]
Amazing work Hussein!

There is one thing that needs to change.

The picture is supposed to be aligned to the left and it needs to take the full height of the card just like the desktop version.

image

**Comment by 3ein39** [comment]
Done

**Review by alikehel — APPROVED** [review]
LGTM.

**Pull request merged**
